name: "CI - CD for gmadmin"
on:
  push: 
    branches:
      - main      
  pull_request:
    branches: 
      - main   
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platform: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/automateforgood:${{ github.sha }}
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    env: 
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Kubectl 
        uses: azure/setup-kubectl@v1

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

#      - name: Deploy the helm chart 
#        run: |
#          helm upgrade --set image.tag="$GITHUB_SHA" --install -f ./gmadmin/values-gm-ns.yaml gmadmin ./gmadmin -n gm    